/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MathCompilerUiModule extends AbstractMathCompilerUiModule {
}
